version: '2'

services:
  es-master:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      BM_ES_NODE_NAME: "es-master"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      BM_ES_MASTER: "true"
      BM_ES_DATA: "false"
    networks:
      - docker_elk
  es-data-1:
    build: elasticsearch/
    ports:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-data-1"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      BM_ES_MASTER: "false"
      BM_ES_DATA: "true"
    networks:
      - docker_elk
    depends_on:
      - es-master
    volumes:
      - ./data-1:/usr/share/elasticsearch/data
  es-data-2:
    build: elasticsearch/
    ports:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-data-2"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      BM_ES_MASTER: "false"
      BM_ES_DATA: "true"
    networks:
      - docker_elk
    volumes:
      - ./data-2:/usr/share/elasticsearch/data
    depends_on:
      - es-master
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d/
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - es-master
    links:
      - es-master:elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - es-master
    links:
      - es-master:elasticsearch

networks:
  docker_elk:
    driver: bridge